title: Open-Architect Blogs
description: A First Principles Journey into Computer Science and Systems Engineering
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

collections:
  posts:
    output: true
